# k8s/service.yml - Trafigi Yonlendiren Service Manifestosu

apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  selector:
    app: go-api
    version: v1 # ⭐️ ÖNEMLİ: Şu an trafiği sadece v1 etiketli Pod'lara yönlendir
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 # Konteynerin çalıştığı port
  type: LoadBalancer # Dışarıdan erişim sağlamak için (Minikube'de bu bir IP adresi verir)